const FETCH_ALL_DRIVERS_REQ = "FETCH_ALL_DRIVERS_REQ" 
const FETCH_ALL_DRIVERS_SUCCESS = "FETCH_ALL_DRIVERS_SUCCESS" 
const FETCH_ALL_DRIVERS_ERROR = "FETCH_ALL_DRIVERS_ERROR" 

const FETCH_ID_DRIVER_REQ = "FETCH_ID_DRIVER_REQ"
const FETCH_ID_DRIVER_SUCCESS = "FETCH_ID_DRIVER_SUCCESS"
const FETCH_ID_DRIVER_ERROR = "FETCH_ID_DRIVER_ERROR"

const FETCH_NAME_DRIVER_REQ = "FETCH_NAME_DRIVER_REQ"
const FETCH_NAME_DRIVER_SUCCESS = "FETCH_NAME_DRIVER_SUCCESS"
const FETCH_NAME_DRIVER_ERROR = "FETCH_NAME_DRIVER_ERROR"

const SUBMIT_DRIVER_REQ = "SUBMIT_DRIVER_REQ"
const SUBMIT_DRIVER_SUCCESS = "SUBMIT_DRIVER_SUCCESS"
const SUBMIT_DRIVER_ERROR = "SUBMIT_DRIVER_ERROR"

const FETCH_TEAMS_REQ = "FETCH_TEAMS_REQ"
const FETCH_TEAMS_SUCCESS = "FETCH_TEAMS_SUCCESS"
const FETCH_TEAMS_ERROR = "FETCH_TEAMS_ERROR"

const FILTER_SOURCE = "FILTER_SOURCE"
const FILTER_TEAM = "FILTER_TEAM" 

const SORT_ALPH = "SORT_ALPH"
const SORT_DOB = "SORT_DOB"